apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: livekit-pvc
  namespace: ai-voice
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
